spring:
  config:
    activate:
      on-profile: management

# management
management:
  endpoints:
    web:
      exposure:
        include: health,info
        exclude: heapdump

  endpoint:
    health:
      probes:
        enabled: true
      show-details: never