spring:
  profiles:
    group:
      local: "local, swagger"
      stag: "stag, datasource, management, swagger"
      prod: "prod, datasource, management, swagger"

  # format
  jackson:
    property-naming-strategy: SNAKE_CASE

  # metadata
  application:
    name: tcg-search
