spring:
  config:
    activate:
      on-profile: stag

app:
  security:
    cors:
      allowed-origins: ${APP_SECURITY_CORS_ALLOWED_ORIGINS}
      allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
      allowed-headers: "Authorization,Content-Type,Accept,Origin"
      exposed-headers: "Location"
      max-age: ${APP_SECURITY_CORS_MAX_AGE:3600}

  auth:
    jwt:
      issuer: ${SECURITY_JWT_ISSUER_URI}
      secret: ${SECURITY_JWT_SECRET}
      access-token-ttl: ${SECURITY_JWT_ACCESS_TOKEN_TTL:15m}
    refresh-token:
      ttl: ${SECURITY_REFRESH_TOKEN_TTL:30d}