spring:
  config:
    activate:
      on-profile: datasource

  # DB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

  # ORM
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        use_sql_comments: false

  # migration
  flyway:
    enabled: true